[project]
name = "app"
version = "0.1.0"
description = "a fastapi microservice"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.0",
    "uvicorn>=0.38.0",
]

[project.scripts]
serve = "uvicorn:main"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
